### ISSUE TITLE
ValueError: Object arrays cannot be loaded when allow_pickle=False

### ISSUE THREAD

**Issue by ghost** [pseeth/soundnet_keras#6]
when loading model:
```
Traceback (most recent call last):
  File "soundnet.py", line 104, in <module>
    prediction = predict_scene_from_audio_file('railroad_audio.wav')
  File "soundnet.py", line 88, in predict_scene_from_audio_file
    model = build_model()
  File "soundnet.py", line 26, in build_model
    model_weights = np.load('models/sound8.npy').item()
```

**Comment by emirkivrak** [comment]
use this:

 model_weights = np.load('models/sound8.npy', encoding='latin1', allow_pickle=True).item()

**Comment by ghost** [comment]
@emirkivrak  thanks it works!
